var img_chunk = {
  start: "iVBORw0KGgoAAAANSUhEUgAAA",
  a: "AAAAAXRSTlMAQObYZgAAAJVJREFUGNNdz8ENgzAMBVAjkQ1gn4zgQ0ylXLi382QEDnEPbNDOU0aoVFzboKrwL3mKvqMYNJTA0xOhg8iv2oY0EKENhhih6w2I0JEloc5wyZUUw2O6LYa81nkpCCHLa15L/Mez3t8OrsyGgacrk8LfcVgUzQY4YdxxEQXYKcn/LvJBRRhFdHpv/9Y5LhjIK16CLV75AiStSc2hKuLGAAAAAElFTkSuQmCC"
};
var IMGS = {
  player: img_chunk.start
  + "B4AAAAeBAMAAADJHrORAAAAFVBMVEUAAAAAAAD///+AgIANR6H6+vohISFo84f0AAAAAXRSTlMAQObYZgAAAJlJREFUGNOl0cENwjAMhWGrsICN4Jy4DJA0CyCUBTh0AC7dfwTi5llBAnHhlxrpaw5xG/rSofQSXLhXsJ3P62o+JfhhGmbvTz/ffdk2hjP7eZjPI8TVYufEqqLKAdYoytIWbJvFlgA3sUYdZnvjPtZ7bJZrveF3LVEkylx8ntzHK4QWtWbypt3hlwnGiZUqTsMH78+4r9SXz16vOx9wcIMkowAAAABJRU5ErkJggg==",
  hurt: img_chunk.start
  + "B4AAAAeBAMAAADJHrORAAAAGFBMVEUAAAAAAAD/UlKAgIC3HByenp76+vohISHDimmpAAAAAXRSTlMAQObYZgAAAK5JREFUGNN90csNwjAMgGFTFsCgwLW4GaA0TBC8QA4dgEvvnLo+dmMrQiB+KZG+Rqr7gB/tU200J6wlO76dlwWx4Gk0P+VwbhaFuYSCzXPAgG49FTULPiwVWS+3dllX9Hm45fMgeWAxauzsmCgTcW+mmImzbHaszrr1ZhFTpGbWK+4dHqM4X/Fgn2uKWW43JH+eO2uPBNZE2gBet7n/ZzDbRAS0afbC22r/a6zbd2+pOyU+8uksHAAAAABJRU5ErkJggg==",
  safe: img_chunk.start
  + "B4AAAAeBAMAAADJHrORAAAAGFBMVEUAAADFyukAAADo6vaAgIAhISE/UbX6+vp2cg3PAAAAAXRSTlMAQObYZgAAAK1JREFUGNOl0VEKwjAMBuB5gwbFAwzF55HV97p6AWsOIEIP4Muub9LfWN/9YYFvhSSlg4Y8Q8tml5EUmimPSCYcX07raj6kAL9M3aPnT99+fRQZfZ4Z87Cfh7A/SbUIBXgrzIVZJpg4FpaihXBsLlamAKuEI3eL/XHv6zOqy7k+sE9eYtF2c/Z9rmK5f/dZ2DJjH3RkdEM+BmByY2Kliml+4fb190pkJcDtKa2o3wNUOtyVj8/uAAAAAElFTkSuQmCC",
  clock: img_chunk.start
  + "A8AAAAPBAMAAADJ+Ih5AAAAD1BMVEUAAAA+JyONbmP//ef/10BIC0P9AAAAAXRSTlMAQObYZgAAAEZJREFUCNdljbENACEMxPK/ARugwATABCj7z4ThCgquiWXJin3pzC5Y6SwDzm0bfpRzUTERW1WElMQ1rohqqPIIZTUY8Dxdjn8J+Xz9xBwAAAAASUVORK5CYII=",
  food: [
    img_chunk.start
    + "A8AAAAPBAMAAADJ+Ih5AAAAD1BMVEUAAABhYWFFWmRCQkJgfYuFDoYnAAAAAXRSTlMAQObYZgAAAExJREFUCNd1isENgFAIQ/uVAUp0gC8uIHED9h9KICae7KUP+pC5UBmEZ/U9IDPh5oYogFIsy6mMAz3t9upxOqvFVm1IQ/vxayyzjS8PuIEGFIvHz+IAAAAASUVORK5CYII=",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAA5ElEQVRYR+2Xyw3CQAxEk0LSAlygB05QK5zoAS6hhRQCClIkPpv1jMcWIJGz1+/teDdK2ubDT8vyt6vFtbbmcL5QPaniEZwiYDVlU0Lqp6TuCXyFwP7UI+IhNbv1snlL4C/wEwkcu446A5thKNa7zwAjMAcfjVwCUfB0gdrOp3nQCaC7R+CuBBABFE4LIPDa1SiJUSNQBORrmAGnR1CK1xKzzgM1AlbAgqcmgMBlgbn4UXiKAAMPF2DhksBr/B54mIAX7hZ43L0ClwVUuFuA+hYziuU3oSpTFFCbsuuffkzYxZH1N7rQ/CFiqq9dAAAAAElFTkSuQmCC",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAAvElEQVRYR+2XYQqAMAiF9dLREaJLGxsVIm2+sWoU9qvgpW+f5hrT4IsH56ffGRBFFFocJLJlEhFh5vNd85xMwHFhYUOv3G5AY23wkaXuAl0BEWUD8zS7yZd1OTVJvz9Xc0AGVDDXREFQzNNkAKFgDXgUvmtA1/sK+0HrMQJhIAgEAXQkup+h3VovAssximMSWgIJr554pfvatvzdveC2JgQCFZswSgDQc3/LupowSjC8BG8ZSHl6DifVA8oGF7bmIf7UuTkAAAAASUVORK5CYII=",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAA+UlEQVRYR+2XzQ3CMAyF4woubMUE7MIg7MIETAUXSoqMlChtXDtOmrZC6QmUn/fh57wUMBs/sLG+aQBRBU4dDDVtedlhpEkCXO/nKgy3y8OoAXBR+HBwONeNh5/d+myAd3f47XG0vRfIKdH/A1SzILUHJFuyLJA21YwXA1CdHQKkWPD8WAMA/vjvPwc0JZbmkha46HUJhd/XSEKnCykAkrfUL5eSMAJY6qhxNkxjHef6CuwaQGMBd3mtUgEUmbu8WIClToEEEOqMeoAD0FrAVSACmHZtaQ5IPaB+I5LSTTNefBlpxObCKakCpULcehGgpji1d/tn1CrwBRw//YF/2DhIAAAAAElFTkSuQmCC",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAAVElEQVRYR2NMqO3+zzCAgHHUAaMhMBoCoyEwGgKjIQCqh2ChsKC5lBG9XsInh68OI9ZMsIXEKial0iTWzFEHjIbAaAiMhsBoCIyGwGgIjIbAgIcAADR7T2v/YpczAAAAAElFTkSuQmCC",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAABQElEQVRYR9WXQRLCIAxF2wvpRq+hZ9Vr6EYvhJNFnJiS/E9Lh9GVtsh/+UAS5mnwZx6sP60CuJwOJQK/P99Nc9KDrejt8QqNu56P33cMDAUg4ploRCMwCAICrBVXKASRAmwVZyBCgF7iCKIKwIjbzaYiaJ/UlmMBgMRVuCaWvYucaAIQARSlCGXjvAs0ACtuI41cskfzByCzvxeAOqQQFEAkbjdiFC1y4f8BJMLMod0dGAZgz3x0/jNnmjZh7Wz7ydFvWzFtLliVB2oR+2dM9AJFA1gX0KbbJRPaDCffd6sFMjmTEaNq2BJ9dQk00ggCpWR27VWnqSNiy61foqwta+oJUfS1SripJ5QJSykFFR3fFdvxXbpiL8DeC+R/XQD8JOzNSMdlEGlXzESA7pYIIuyKe4hbuAhk0ZD0FvYOeZAP+dBwMN5T1aoAAAAASUVORK5CYII=",
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAA0klEQVRYR+2XUQ6DMAiG5Qomu/8BTbwChlrm3462bkZ8GH0x1rZ8/CUgNH0ONuZum6LqZGb2sU+0m0YAH8vZY3FUIBTA3XMEeMTzAoCX9bYgw4PpNU9qOABCgVAgFOhmQk1MKXFAktJ3eeqQ7/g+nM81wASoM2ILIFWxARyCFQ61AKx0/AsAwpn7vQHqKzFrgSxqSmbEQO8KLiuAsmlwfQM33NMLQiydZ6P77Lr3VVgA8T8QCoQCf6lAzgupQeMnFNC20B1APdfMmABc2qLDSNGRb9zBhRRRgvDsAAAAAElFTkSuQmCC"
  ],
  shield: img_chunk.start
  + "A8AAAAPBAMAAADJ+Ih5AAAAD1BMVEUAAAAPFUsBV5swP58aI377u/SMAAAAAXRSTlMAQObYZgAAAE9JREFUCNdNzcEJADEIRFGxA7NbQLSDYAWC/de0Mx7CSgif50HBxJ4/1EPRvsLwEMZhZJ7uQjyMu/pHWFeetUX9rbQQARVBQEYYIgwR7vUPPG8LGKIqw/AAAAAASUVORK5CYII=",
  a: [
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAABMr1D///8AAACtUrGj"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAAD0Qzb///8AAABi95rX"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAAAhlvP///8AAADsv1b1"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAAD/6gD///8AAACeE2jF"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAACCdxf///8AAACJA08n"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAACcJ7D///8AAAA6K8ji"
    + img_chunk.a,
    img_chunk.start + "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAACCdxf///8AAACJA08n"
    + img_chunk.a
  ]
};

function imgBase64(img) {
  return "data:image/png;base64," + img;
}