var img_chunk = {
  start: "iVBORw0KGgoAAAANSUhEUgAAA",
  a: "AAAAAXRSTlMAQObYZgAAAJVJREFUGNNdz8ENgzAMBVAjkQ1gn4zgQ0ylXLi382QEDnEPbNDOU0aoVFzboKrwL3mKvqMYNJTA0xOhg8iv2oY0EKENhhih6w2I0JEloc5wyZUUw2O6LYa81nkpCCHLa15L/Mez3t8OrsyGgacrk8LfcVgUzQY4YdxxEQXYKcn/LvJBRRhFdHpv/9Y5LhjIK16CLV75AiStSc2hKuLGAAAAAElFTkSuQmCC",
  a2: "B4AAAAeAgMAAABGXkYxAAAADFBMVEUAAA"
};
var IMGS = {
  player: img_chunk.start
  + "BQAAAAcBAMAAACT9IJTAAAAFVBMVEUAAAAAAAD///+AgIANR6H6+vohISFo84f0AAAAAXRSTlMAQObYZgAAAI9JREFUGNONzsENwjAMBdBPwwAkBc7Nn6DIC4DkBTh0AC7dfwS+m8Cll34pzotixQGsB0iPvGWcYXlZ3mGD3bQ16r53HOf9x3X9jHr3/1iynhk4XV15XQDUwkrWAgzMrFllAoNRCArqKY1Fh6A7g3SHGXNVq2lEHxcjErdIQCN2nIZO9+fZPZT0v1iimbXyBUHtH8q57nzcAAAAAElFTkSuQmCC",
  hurt: img_chunk.start
  + "BQAAAAcBAMAAACT9IJTAAAAGFBMVEUAAAAAAAD/UlKAgIC3HByenp76+vohISHDimmpAAAAAXRSTlMAQObYZgAAAJ9JREFUGNNlzbENwjAQBdBPzAB8hUAbnTxA0C0AkRdI4QFo0lNlfe4npuJLPj/bZx3gLUB6cE8/wbmubw6kw28khyrqvVZW9uKwLFzEuAtQ1P4j9Z93Udm2Tw9niyN5ywScX7q7PgHk2bJZnoHOiuUSZYSJKgYLRM8sBuIgkiYaCXcrOVpdI8oejUi2JwQcxB/HrpG8nEgpuU9aQXc/yheqsiUCe3feWwAAAABJRU5ErkJggg==",
  safe: img_chunk.start
  + "BgAAAAeBAMAAADEAMPWAAAAGFBMVEUAAAADqfQAAADo6vaAgIAhISE/UbX6+vri2c65AAAAAXRSTlMAQObYZgAAAKtJREFUGNOVkMsNAjEMRE0HsVgoYAXivBqlgEVpACJz50AK4LLtM84HzowUy0+2PI5FdtoVRERTl7IwXeeq0xpYmLft7ZSUcGEygF297384/8DsTqDPdzQ3SF3cQPTwKNTrpkKIGRGI2RfdwxCNYeGicPAAJTBlZx6QiQ1KgQNKcdMEizCkZmpVzXRC1UofUgPPadsgDFj2Azj8efTBlP9h9TfOqzU4UKFeXz5PHDoo1D2ZNAAAAABJRU5ErkJggg==",
  clock: img_chunk.start
  + "A8AAAAPBAMAAADJ+Ih5AAAAD1BMVEUAAAA+JyONbmP//ef/10BIC0P9AAAAAXRSTlMAQObYZgAAAEZJREFUCNdljbENACEMxPK/ARugwATABCj7z4ThCgquiWXJin3pzC5Y6SwDzm0bfpRzUTERW1WElMQ1rohqqPIIZTUY8Dxdjn8J+Xz9xBwAAAAASUVORK5CYII=",
  earth: img_chunk.start
  + "B8AAAAfAgMAAABiwP6qAAAADFBMVEUAAAAAaL00aSwAeL5dV4+MAAAAAXRSTlMAQObYZgAAAJFJREFUGNNNzbENAyEMBVBfJEZgiUzBCBRnCvprMs+xwVHYWSIjZYT8b3RSfgFPsvkI4qdEnj4r74e7v4lEfIDsyBfQF3CJbIGJlYUCdMCKZGJoBZrbDKjPA1DVPlV3otlBIH0QjN1oN/oCmubOHnRbJfjtH1LASqAT23olIoETyBxVIGHZCrABQyRm6I3oheMHl2pVxdCHzD8AAAAASUVORK5CYII=",
  food: [
      // commutator
    img_chunk.start
    + "B0AAAAbCAMAAAC3FHQgAAAAY1BMVEUAAABCQkKNiZekoLF6doXq5fm5tcZmYnPQy9+YlKVMSFevq7xFQk39+v/59v7j3vLV0OR2coNzcHsbFyXFws2dmqVmY2xfXGcnJC8QDBzDvtI5NkEvKjsiHi2qp7IDABABAAfKQE0KAAAAAXRSTlMAQObYZgAAAMZJREFUKM/N0leyAiEQBdB3u5vM5GR8uv9VKmUYdUa+5Qvq0Inib2XhsfkRRBZzGZDJgCdmSiKL683mAoFM4Dj891gE4oZx8t6XBVaKYWgaEhGvSiwbGVsiF9g1wj0WsxviUOmaA/m+++xchLneFaoKronHRHhpyxBrW6hS7ZiivFraylVrVRaVdaab7X6NUmylVH04bc+HmW6rFdI2WGu6o494o3SQgUhrFjJxA9xt5jSvYzJTwuUzjyStmfZbfPlr+26zahf0bwbz2yRmLAAAAABJRU5ErkJggg==",
      //battery
    img_chunk.start
    + "B0AAAAeAgMAAACtaf0yAAAADFBMVEUAAAD///+3HBxONC5tM5iQAAAAAXRSTlMAQObYZgAAAF9JREFUGNOFz7EJwDAMBEBDZpQLbxDvoxFc6KfIEtkm4ARZj5qAvxDXPLxKKcd8vpuYK1fiFs8GDRiEOjogAVsABqGOCsAIrzewLoAELMB6hRISMM4YhAa6BM7/8fnpCzU4gbY+/hfSAAAAAElFTkSuQmCC",
      //toolbox
    img_chunk.start
    + "CAAAAAfBAMAAAB0eNK/AAAALVBMVEUAAACpWFbqlpq0PUCUm6unutmn1O1lMzPM0tW5hjLrxhi5wMfGy9adyeO4xNp1/pqrAAAAAXRSTlMAQObYZgAAAMxJREFUKM+dz7ENwjAQBVBHDiWFcUGLnAVwDok2xRUpKNIkG8QrRPQULunYgRVYgEXYg7ucwVI6+N09+X/JKmfVq5QSEfnuPnB6xojqNaYTMcZ4wWYgWPP7R0uA5Qz9DIhtbGgj9LKCjUKBENIsHFAgzfrt+X5lGOWBNtMMQ+g0AINNMCqzcXtuMHCjMHUGbhjr3I4mGG4TATVcRcA5EkymFpBY8AKFyXEMPt/2d6j/BViChgWQ+Az8faYvgJKAF6BCigYgqKiQAwB8vwFrOkas381RfQAAAABJRU5ErkJggg==",
      //freq amplifier
    img_chunk.start
    + "CAAAAAXAgMAAAAXa6VyAAAADFBMVEUAAAB8s0IJAgH///9NXvGcAAAAAXRSTlMAQObYZgAAAFBJREFUCNd1z8EJwEAIBMB9pz+FKyAl3f/eW0VKi7rBBML5GnYREWANgGkxnqD5EDrZV73lWV2dvFjCETinjQCV8IOs+CSFJWirACX4n+gvbrDCRDJyLc4LAAAAAElFTkSuQmCC",
      //transistor
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAAVElEQVRYR2NMqO3+zzCAgHHUAaMhMBoCoyEwGgKjIQCqh2ChsKC5lBG9XsInh68OI9ZMsIXEKial0iTWzFEHjIbAaAiMhsBoCIyGwGgIjIbAgIcAADR7T2v/YpczAAAAAElFTkSuQmCC",
      //antenna
    img_chunk.start
    + "BoAAAAeCAYAAAAy2w7YAAACFElEQVRIS52Wu1XEMBBFx81QANFmdgUUQAEUQETmcTNbABGhHEECOTRjzht5rNHP0q7O2eP1T9fvzdNnoDsbM2+1V5l5SO9lF864tvNpmmgcx+jxdV3l3DknRwvsAilgnucu/QB6GBMzCSOA1AojOwWgg2kcya1rpib9ghRWAInoARBVgIfQuYWgo9S6Euzl9Y3+fr6GxDpfYGYiQKyCEqQHtiwLXd8/jHX750AJg4RfZ3OFYOirRZDaNQyLFJK2aoKjT8BTqTo9z0AHRCKyEG0zEZzdtqg+amF6rNWrDpKq7SCB3gcrKgqWERF8UEVq0B2wc9AxsoyiG2C2cLAStqFJ6uLaVBTdAAPAqslBqI3YtteIZn+ethMb9VGrBum9vl9uVFRRhsuYOdBUkU6ssE1mhjwIRlnfMKpCVE0M0iCoffbYmCF0kg0TqX9B1RwZi1Thaglma7jfd65sl8f42kBNBNKF7LjagAGis4HGOAiPIQdI+MmyIOkrwOxalANyJUd+9A8zumUqLdFpicqAOiRS5FXpyOlfImw98F9rkg2/UqAeHi8S7Oenr0bekKyLPFMDZNadAVu0FiSzrtWh3ofi3+9PWpYhivDZ+13brRAY3TQyzfO2z86hnrq1KgG7QLrtQiLR0vlMlv292UFqgU0QkjhNLtpapTvS0KEHlmBNkI19CgzjKQBqCewC2RCcFfwsff++sNw1wBQfPgAAAABJRU5ErkJggg==",
      //guide
    img_chunk.start
    + "CAAAAAgCAYAAABzenr0AAAA0klEQVRYR+2XUQ6DMAiG5Qomu/8BTbwChlrm3462bkZ8GH0x1rZ8/CUgNH0ONuZum6LqZGb2sU+0m0YAH8vZY3FUIBTA3XMEeMTzAoCX9bYgw4PpNU9qOABCgVAgFOhmQk1MKXFAktJ3eeqQ7/g+nM81wASoM2ILIFWxARyCFQ61AKx0/AsAwpn7vQHqKzFrgSxqSmbEQO8KLiuAsmlwfQM33NMLQiydZ6P77Lr3VVgA8T8QCoQCf6lAzgupQeMnFNC20B1APdfMmABc2qLDSNGRb9zBhRRRgvDsAAAAAElFTkSuQmCC"
  ],
  shield: img_chunk.start
  + "A8AAAAPBAMAAADJ+Ih5AAAAD1BMVEUAAAAPFUsBV5swP58aI377u/SMAAAAAXRSTlMAQObYZgAAAE9JREFUCNdNzcEJADEIRFGxA7NbQLSDYAWC/de0Mx7CSgif50HBxJ4/1EPRvsLwEMZhZJ7uQjyMu/pHWFeetUX9rbQQARVBQEYYIgwR7vUPPG8LGKIqw/AAAAAASUVORK5CYII=",
  a: [
    img_chunk.start + img_chunk.a2 + "BMr1D///8AAACtUrGj"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "D0Qzb///8AAABi95rX"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "AhlvP///8AAADsv1b1"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "D/6gD///8AAACeE2jF"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "CCdxf///8AAACJA08n"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "CcJ7D///8AAAA6K8ji"
    + img_chunk.a,
    img_chunk.start + img_chunk.a2 + "CCdxf///8AAACJA08n"
    + img_chunk.a
  ],
  satellite:
      img_chunk.start + "DMAAAAzCAMAAAANf8AYAAAAPFBMVEUAAABcuspQl6FcuspcucpFd4jwyTTxyjVLh5g5UmVdvc1cuspgxdNIjphQl6Gy6/LxyjNewdBDcoNNlJ6+gVZ2AAAACHRSTlMA9/fu3P7tahwiW/UAAAEBSURBVEjH5dTRTgQhDAVQxl0V2i2zrv//r7bCBDBk6PXBxOx9PyG3KQ0lKcBJKeGEFKGEFGEkRopREUAoagwBhAoiBFVCEDIy73TdT9C808aXfdWJRsSaA73d36edaHyJv7OJ5a6ZdaJxenzEXlI060Q/pscdEgnimR63iALxTK+Rj9uuxrMRHbkpEtdGNGJIFhvRGhkpEce3sN4bk5Ka040oRPN48AEWqJKCqDOLcyIln69hSSwdyTmH4CBhIPmlouAmZnxBiWUkyWX4INl/ljfuCfnQhTtCTnQ19GRn+RT9vhMhqJ1lsFNxEKL/ML0/2wiA4N9iPMsYgkg7y3Aq+QJ87R4vVqQ+lgAAAABJRU5ErkJggg=="
};

function imgBase64(img) {
  return "data:image/png;base64," + img;
}